name: voca_notes
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #? State Management
  flutter_bloc: ^8.1.6

  #? Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0

  #? Locale
  slang: ^4.4.0
  slang_flutter: ^4.4.0

  #? Dev Utils
  auto_route: ^9.2.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  logger: ^2.5.0
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.3
  jiffy: ^6.3.2

  #? Interface Utils
  collection: ^1.18.0
  dart_helper_utils: ^3.3.0
  flash: ^3.1.1
  flutter_svg: ^2.0.16
  table_calendar: ^3.1.3
  font_awesome_flutter: ^10.8.0
  skeletonizer: ^1.4.2
  window_size: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  slang_build_runner: ^4.4.0

flutter_gen:
  output: lib/gen/
  line_length: 80
  parse_metadata: true
  integrations:
    flutter_svg: true
    rive: true
    lottie: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
      style: dot-delimiter
      class_name: Assets
    exclude: []
  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/images/backgrounds/
    - assets/images/dictionary/
    - assets/fonts/dmSans/
    - assets/fonts/dmSerifDisplay/
    - assets/svgs/
    - assets/svgs/appIcons/
  fonts:
    - family: DM Serif Display
      fonts:
        - asset: assets/fonts/dmSerifDisplay/DMSerifDisplay-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/dmSerifDisplay/DMSerifDisplay-Italic.ttf
          weight: 400
          style: italic
    - family: DM Sans
      fonts:
        - asset: assets/fonts/dmSans/DMSans-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/dmSans/DMSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/dmSans/DMSans-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/dmSans/DMSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/dmSans/DMSans-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/dmSans/DMSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/dmSans/DMSans-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/dmSans/DMSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/dmSans/DMSans-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/dmSans/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/dmSans/DMSans-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/dmSans/DMSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/dmSans/DMSans-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/dmSans/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/dmSans/DMSans-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/dmSans/DMSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/dmSans/DMSans-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/dmSans/DMSans-BlackItalic.ttf
          weight: 900
          style: italic
